# Numpy

In [1]:
# How to import the NumPy library
# np is an alias, you may use other alias (np is standars in the industry)
import numpy as np

In [2]:
# Create 1-D array using list/tuple
# Use np.array()

fromList_to_1dArray = np.array([10,20,30,40,50])
fromTuple_to_1dArray = np.array((1,2,3,4,5))

print(type(fromList_to_1dArray))
print(fromList_to_1dArray)

print(type(fromTuple_to_1dArray))
print(fromTuple_to_1dArray)

<class 'numpy.ndarray'>
[10 20 30 40 50]
<class 'numpy.ndarray'>
[1 2 3 4 5]


In [3]:
# Create 2-D array using 2 lists
# axis = 0 represents rows (Axis 0 is running vertically downwards across the rows)
# axis = 1 represents coulumns (Axis 1 is running horizontally from the left to the right across the columns)
# axis = 2 represents depth layers (Axis 2 is running from the from to the back of the layers)
fromLists_to_2dArray = np.array([[1,2,3,4,5],[5,6,7,8,9]])
print(type(fromLists_to_2dArray))
print(fromLists_to_2dArray)

<class 'numpy.ndarray'>
[[1 2 3 4 5]
 [5 6 7 8 9]]


In [4]:
# Sum two list elements
# 1. You can use fro loop & indexing, perform Operation
# 2. You can write inline function
num_list1 = [1,2,3,4,5,6,7,8,9]
num_list2 = [11,12,13,14,15,16,17,18]

sum_list = list(map(lambda x, y: x+y, num_list1,num_list2))
print(sum_list)
# evenif the 2 list are not the same number of elements, it execute with the smallest list

[12, 14, 16, 18, 20, 22, 24, 26]


In [5]:
# Use numpy arrays --> more efficient/simple than to use Lanbda functions but need same nb of elements in each array
# 1D Array
num_array1 = np.array(num_list1)
num_array2 = np.array([11,12,13,14,15,16,17,18,19])

sum_array = num_array1+num_array2
print(sum_array)

[12 14 16 18 20 22 24 26 28]


In [6]:
# Creation of arrays of fixed size
# from list
array_from_list1 = np.array([1,2,3,4,5])
array_from_list2 = np.array([1,2,3,4,5],dtype=float)
# from tuple
array_from_tuple = np.array((6,7,8,9,10))

print(array_from_list1)
print(array_from_list2)
print(array_from_tuple)

[1 2 3 4 5]
[1. 2. 3. 4. 5.]
[ 6  7  8  9 10]


## Numpy Fundamentals
#### Python Library Name: NumPy - NUMerical PYthon 
<b>   Used for scientic computing and data analys </b><br>
<b>   Uses n-dimentional, homogenous objects (`ndarray`) </b><br>
<b>   Provide tools fro integrating C,C++ ... </b><br>
Power of NumPy is N-Dimentioanl array object which is in the form of rows and columns <br>
Why Numpy? Why can't list/tuple/set...
-  Fast
-  Less Memory
-  Convenient
-  Vectorized code (code does not contain explicit looping & indexing ...)

#### Numpy Fundamentals
<b> NumPy arrays Generation <br>
Strucutre and contetn of arrys<br>
Indexing - Subsetting -Slicing -Iterating through arrays <br>
Vectorised code <br>
Speed of excecution of NumPy and standard Python lists </b>

In [7]:
# condition statement as an arguement tp np.array()
array_from_list3=array_from_list1 >=3
print(array_from_list3)

[False False  True  True  True]


In [8]:
# How to fetch the actual elements
array_from_list1[array_from_list3]

array([3, 4, 5])

In [9]:
# 2D Array
array1 = np.array([[1,2,3,4,5],[5,6,7,8,9]])
print(array1)

array2 = np.array([[10,20,30,40,50],[50,60,70,80,90]])
print(array2)

[[1 2 3 4 5]
 [5 6 7 8 9]]
[[10 20 30 40 50]
 [50 60 70 80 90]]


In [10]:
array2 - array1

array([[ 9, 18, 27, 36, 45],
       [45, 54, 63, 72, 81]])

In [11]:
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.  This argument can only be used to 'upcast' the array.  For
        downcasting, use the .astype(t) method.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', 'C', 'F'}

#### How to iniatialize np array when size is known
function that are used to do so are : <br>
-  np.arange(): Array creation whith defined increments
-  np.zeros(): Array of 0s
-  np.ones(): Array of 1s
-  np.ramdom.ramdom(): Array of ramdow numbers
-  np.random.randint(): Randow array of integers within a particular range
-  np.linspace(): array of dixed length
-  np.full(): constant array with any number 'n'
-  np.eye():identify matrix array
-  np.tile(): array is going to be created many times


In [12]:
# np.range()
# range()

increment = np.arange(1,15,2)
increment

array([ 1,  3,  5,  7,  9, 11, 13])

In [13]:
decrement = np.arange(50.,10.,-10)
decrement

array([50., 40., 30., 20.])

In [14]:
# Zeros init
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [15]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
# oness init
np.ones(5)

array([1., 1., 1., 1., 1.])

In [17]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [18]:
np.ones((5,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [19]:
# random numbers Array
np.random.random([3, 3])

array([[0.82356197, 0.82475176, 0.69038798],
       [0.17695288, 0.1840635 , 0.38122185],
       [0.78010745, 0.96655941, 0.66817804]])

In [20]:
# Create a 3 * 5 randow array of integers ranging from 0 to 9
np.random.randint(1,10,(3, 5))

array([[3, 1, 4, 7, 9],
       [2, 5, 2, 6, 9],
       [4, 8, 4, 1, 7]])

In [21]:
# np.full() default data type int
np.full(2,5)

array([5, 5])

In [22]:
np.full((2,3),5)

array([[5, 5, 5],
       [5, 5, 5]])

In [23]:
# Identify matrix
i_matrix = np.eye (5,dtype =int)
i_matrix

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [24]:
# np.linspace()
# length know, step size unknow
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [25]:
# Reporting array for number of times - default type is int
array1=([5,4,3])
np.tile(array1,5)

array([5, 4, 3, 5, 4, 3, 5, 4, 3, 5, 4, 3, 5, 4, 3])

In [26]:
np.tile(array1,(2,5))

array([[5, 4, 3, 5, 4, 3, 5, 4, 3, 5, 4, 3, 5, 4, 3],
       [5, 4, 3, 5, 4, 3, 5, 4, 3, 5, 4, 3, 5, 4, 3]])

#### Structure of Arrays
<b> How to find out type of arrays : </b> <br>
-  dtype: finds data type of arrays
-  shape: shows shape of array (n* m)
-  itemsize: ,e,ory used by each array elements in bytes
-  ndim: numbers of axes (or dimensions)

In [27]:
array1=np.ones((5,3))
array1

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [28]:
# find dtype, shape,itemsize and ndim of array 1
print(array1.dtype)
print(array1.shape)
print(array1.itemsize)
print(array1.ndim)

float64
(5, 3)
8
2


In [29]:
# Create a 3-D array
# reshape() simply reshapes a 1-D array
# reshape(2,3,2) --> 2 columns ,3 rows , 2 segments
# arange(12) --> elements from 0 to 11
# 12 =2 * 3 * 2
array_3d = np.arange(12).reshape(2,3,2)
array_3d

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

#### Indexing, Subsetting, Slicing and Iterating though Arrays

In [30]:
# Indexing and slicing one dimentional arrays
array1d = np.arange(5)
array1d

array([0, 1, 2, 3, 4])

In [31]:
# access through indexing
array1d[2]

2

In [32]:
array1d[2:4]

array([2, 3])

In [33]:
# subset with an increment
array1d[0::2]

array([0, 2, 4])

In [34]:
# iterations are also similar to lists
for i in array1d:
    print(i*2)

0
2
4
6
8


In [35]:
# 2-D array accessing
array2d = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(array2d)
print(array2d.ndim)
print(array2d[1,3])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
2
8


In [36]:
# slicing all columns (here 3rd)
print(array2d[2,:])

[ 9 10 11 12]


In [37]:
# slicing all rows (here 1st)
print(array2d[:,0])

[1 5 9]


In [38]:
# slicing all rows and the first 2 columns
print(array2d[:,:2])

[[ 1  2]
 [ 5  6]
 [ 9 10]]


In [39]:
# slicing all columns and the first 2 rows
print(array2d[:2,:])

[[1 2 3 4]
 [5 6 7 8]]


In [40]:
# slicing the first 2 columns and the first 2 rows
print(array2d[:2,:2])

[[1 2]
 [5 6]]


In [41]:
# slicing the last 2 columns and the last 2 rows
print(array2d[1:,2:])

[[ 7  8]
 [11 12]]


In [42]:
# Iterating over 2D/3D arrays (row wise and column wise)
for row in array2d:
    print(row)

[1 2 3 4]
[5 6 7 8]
[ 9 10 11 12]


#### Execution speed in NumPy and Standard Python Lists
NumPy is much faster

In [43]:
# import time library
import time

In [44]:
# create 2 large lists
Large_list1=[i for i in range (2000000)]
Large_list2=[j**2 for j in range (2000000)]

# capture start time and end time
start_time = time.time()
perform_Ops = list(map(lambda x ,y:x*y,Large_list1,Large_list2))
end_time = time.time()
duration = end_time-start_time
print(duration)


0.9418001174926758


In [45]:
# numpy array
array1=np.array([i for i in range (2000000)])
array2=np.array([j**2 for j in range (2000000)])

# capture start time and end time
start_time_np = time.time()
perform_Ops2 = array1*array2
end_time_np = time.time()
duration_np = end_time_np-start_time_np
print(duration)

0.9418001174926758


Not true !!!!

## NumPy arrays - Few operations
##### Basic mathematical operation / linear algebra operations / functions
##### Playing with arrays using resize /reshape /stack creation

Playing with array

In [46]:
# if the array don't have the same dimentions
# use resize()

sample_array = np.arange(0, 12)
print(sample_array)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [47]:
print(sample_array.size)

12


In [48]:
print(np.resize(sample_array,(3,4)))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [49]:
print(np.resize(sample_array,(6,4)))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [50]:
# give a shape to an array without chaging its data
sample_array = np.arange(0,9).reshape(3,3)
sample_array

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [51]:
# dimensions are automatically calculated when you use -1
sample_array = np.arange(0,9)
x = sample_array.reshape(3,-1)
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [52]:
# transpose
x.T

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [53]:
# adding elements at the end of the array
y = np.append(sample_array,[10,11])
y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8, 10, 11])

In [54]:
# insert element at a given index
z=np.insert(y,9,9)
z

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [55]:
# delete element given an index array
print(y)
z=np.delete(y,[9])
z

[ 0  1  2  3  4  5  6  7  8 10 11]


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8, 11])

Split / Join / Stack Arrays
-  np.r_() Arrange array row-wise
-  np.c_() Arrange array row-column
-  np.concatenate() Concatenate 2 arrays
-  np.hstack() stack arrays horizontally
-  np.vstack() stack arrays vertically

In [56]:
# Create 2-D arrays
array1 = np.arange(9).reshape(3,3)
array2 = np.arange(12).reshape(3,4)

print(array1)
print(array2)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [57]:
# Concateante
#print(np.concatenate((array1,array2)))
# thow an error due to improper dimention
array3 = np.arange(9,18).reshape(3,3)
array3

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [58]:
print(np.concatenate((array1,array3)))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]


In [59]:
# Stack the array element horizontally
np.hstack((array1,array3))

array([[ 0,  1,  2,  9, 10, 11],
       [ 3,  4,  5, 12, 13, 14],
       [ 6,  7,  8, 15, 16, 17]])

In [60]:
# Stack the array element vertically
np.vstack((array1,array3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [61]:
# Stack arrays row-wise
#print(np.r_(array1,array3)) # () need to be []

In [62]:
print(np.r_[array1,array3])

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]


In [63]:
# Stack arrays column-wise
print(np.c_[array1,array3])

[[ 0  1  2  9 10 11]
 [ 3  4  5 12 13 14]
 [ 6  7  8 15 16 17]]


Basic Mathematical operations / linear algebra operations / functions

In [64]:
# Apllying math operations
sample_array = np.arange(10,20)

In [65]:
# explomential, logarithms,trigonometry -sine& cosine
print('exponetial value a sample_array')
print(np.exp(sample_array))
print('logarithms value a sample_array')
print(np.log(sample_array))
print('sine value a sample_array')
print(np.sin(sample_array))
print('cosine value a sample_array')
print(np.cos(sample_array))

exponetial value a sample_array
[2.20264658e+04 5.98741417e+04 1.62754791e+05 4.42413392e+05
 1.20260428e+06 3.26901737e+06 8.88611052e+06 2.41549528e+07
 6.56599691e+07 1.78482301e+08]
logarithms value a sample_array
[2.30258509 2.39789527 2.48490665 2.56494936 2.63905733 2.7080502
 2.77258872 2.83321334 2.89037176 2.94443898]
sine value a sample_array
[-0.54402111 -0.99999021 -0.53657292  0.42016704  0.99060736  0.65028784
 -0.28790332 -0.96139749 -0.75098725  0.14987721]
cosine value a sample_array
[-0.83907153  0.0044257   0.84385396  0.90744678  0.13673722 -0.75968791
 -0.95765948 -0.27516334  0.66031671  0.98870462]


In [66]:
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [67]:
# Executing a function in a non-numpy way
# BEDMAS
non_numpy_fn = [(x**2+2*x+3) for x in sample_array]
print(non_numpy_fn)

[123, 146, 171, 198, 227, 258, 291, 326, 363, 402]


In [68]:
# Vectorized the function and apply on a numpy array
vectorized_fn =np.vectorize(lambda x : (x**2+2*x+3))
vectorized_fn(sample_array)

array([123, 146, 171, 198, 227, 258, 291, 326, 363, 402])

In [69]:
# Apply vectorized function code on a 2-D array
vectorized_fn(array3)

array([[102, 123, 146],
       [171, 198, 227],
       [258, 291, 326]])

##### Linear Algebra Operation
-  help(np.linalg) Provides linear algebra docuementation
###### np.linea - is a package
-  np.linalg.inv : Inverse of a matrix
-  np.linalg.det : Determinant of a matrix
-  np.linalg.eig : Eigenvalues and eigenvectors of a matrix
-  np.dot(a,b)   : dot product of two matrices    


In [70]:
# Create 2-D arrays
array1 = np.arange(5,14).reshape(3,3)
array2 = np.arange(1,13).reshape(3,4)

print(array1)
print(array2)

[[ 5  6  7]
 [ 8  9 10]
 [11 12 13]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [71]:
# Determinant of 3x3 matrix vs 3x4 matrix
print(np.linalg.det(array1))
#print(np.linalg.det(array2)) # not possible for non-square matrix

0.0


In [72]:
# Inverse of matrix
#print(np.linalg.inv(array1))
#print(np.linalg.inv(array2)) # not possible for non-square matrix

In [73]:
# Eigenvalues and eigenvectors of a matrix
np.linalg.eig(array1)

(array([ 2.76509717e+01, -6.50971698e-01,  6.66880826e-16]),
 array([[-0.37636677, -0.75529416,  0.40824829],
        [-0.55798202, -0.05094566, -0.81649658],
        [-0.73959727,  0.65340284,  0.40824829]]))

In [74]:
# dot product of two matrices
# n x m vs m x p
np.dot(array1,array2)

array([[ 98, 116, 134, 152],
       [143, 170, 197, 224],
       [188, 224, 260, 296]])